### ISSUE TITLE
Not sure if this is the right place... need help with quick and easy faqs

### ISSUE THREAD

**Issue by sfaught** [InspiryThemes/quick-and-easy-faqs#1]
I want to be able to place different faqs on different pages?  Example... My Accounts page will list all questions related to accounts such as... Billing, Invoice, payment, etc.  I want to have another page titled Available Services and it will list only those such as front-load, roll-off, etc.  I want only those faqs listed under the page and not all faqs on one page.  Is this possible?  I am sure it probably is and I am just not sure how to set it up, if you could let me know that would be great.  Thank, your!!!

**Comment by saqibsarwar** [comment]
Hi,

You can filter FAQs using filter attribute 

Example: filter="group-slug,another-group-slug" 

Check documentation at https://github.com/saqibsarwar/quick-and-easy-faqs for details.

Regards
