### ISSUE TITLE
change FAQs order

### ISSUE THREAD

**Issue by wernerkarlheisenberg** [InspiryThemes/quick-and-easy-faqs#10]
Is there a possebility to change the order in which the FAQs are displayed. I want a certain FAQ to be displayed first. Very nice plugin by the way!

**Comment by fahidjavid** [comment]
Hi,

Thanks for your good words for this plugin. You can use the following plugin to reorder your any Posts, Pages and Custom Post Types.

: https://wordpress.org/plugins/post-types-order/

Kind Regards,

Fahid
