### ISSUE TITLE
Quick and Easy FAQ's not working on WordPress site.

### ISSUE THREAD

**Issue by uniquejay57** [InspiryThemes/quick-and-easy-faqs#11]
I installed Q&E FAQ's on my WP site and had it up and running. Now it no longer works and my site goes live on 12/15. 
Now what!
When I click on Settings I get "Cannot load quick_and_easy_faqs."
I can see them in the FAQ's tab but not on my site.

**Comment by hassanrazmy** [comment]
Hi,

Sorry for the delayed reply. 

The quick and easy FAQs plugin works perfectly with all standard WordPress installations. We address development issues on GitHub. Please visit the following support forum for this kind of specific problem.

https://wordpress.org/support/plugin/quick-and-easy-faqs

Thanks & Regards
