### ISSUE TITLE
Remove font awesome icon font (2)

### ISSUE THREAD

**Issue by elkegepunkt** [InspiryThemes/quick-and-easy-faqs#16]
I return to the closed issue "[Remove font awesome icon font](https://github.com/InspiryThemes/quick-and-easy-faqs/issues/6)".

What would you think about adding a simple on / off switch to load (or not load) the Font Awesome Styles? :)

But, just an idea of mine. Because FA is already loaded on my site and I reluctant to load styles or scripts that are already present and thus unnecessarily loaded.

Anyway, thanks for your excelent work, I appreciate it.

Regards, Elke

**Comment by sungraiz** [comment]
Hi @elkegepunkt 

Thanks for the suggestion.

We'll definitely consider it and will be available in the next update.

Kind Regards,
