### ISSUE TITLE
To Allow for multiple FAQs on the same page with different filter categories

### ISSUE THREAD

**Issue by ARChilton** [InspiryThemes/quick-and-easy-faqs#19]
https://github.com/InspiryThemes/quick-and-easy-faqs/blob/b7133095f0062ca8de76312441e438c25b653df4/frontend/js/scripts.js#L48

If you change the line above to:

allFAQs = $(this)
        .closest('.qae-faqs-container')
        .find('.qe-faq-toggle, .qe-faq-list, ol.qe-faqs-index-list li')

I think this will solve the issue I found whereby two FAQs on the same page will conflict with each other. This traverses up to the FAQ's container then finds the classes rather than finds them across the whole DOM.

**Comment by sungraiz** [comment]
Hi,

Thank you for pointing out and providing the issue fix. We'll definitely look into it while working on the next update.

Regards,
