### ISSUE TITLE
fonts and weird spacing

### ISSUE THREAD

**Issue by garretthope** [InspiryThemes/quick-and-easy-faqs#2]
Hi!

Thank you for the plugin! It's working well, but I have two questions.

First question, I was able to customize the font for the answers, but I can't figure out what code to type in order to customize the questions inside the toggle. What CSS code should I use to costumize the questions?

Second questions, the plugin is putting funny spacing before and after the first question, and then after the last question. You can see this at: http://composeronfire.com/coaching-faq/. How can I eliminate this spacing and make it consistent throughout the page?

Thank you for your help!

**Comment by saqibsarwar** [comment]
This plugin uses your current theme's css styles to display FAQs

FAQs are sorted in the order they are published and you can change the order by changing published date & time.

**Comment by garretthope** [comment]
This is an absolutely unhelpful response.

I didn't have a question about the order of the FAQs. The question was about changing the font of the FAQ answer. I was able to customize the font of the question, but not the answer. What CSS code should I use to customize the font of the answers? If the answers were pulling the font from my theme's css files it would be consistent with the rest of my site, but it's not. 

If you are unable to help me with the spacing of the questions could you at least point me in the right direction? Just telling me that it's in the theme's css files is useless information. My theme developer tells me the code is in the plugin.
