### ISSUE TITLE
Accoridon / Group JS console error. Groups not expanding

### ISSUE THREAD

**Issue by dm1988** [InspiryThemes/quick-and-easy-faqs#36]
On a fresh WP setup, version 6.5.2, when faq are grouped, i.e. [faqs style="grouped"], [faqs style="toggle-grouped"], [faqs style="accordion"], a console error is logged relating to JQuery. The groups are not expanding when clicked.

The error is:
```
Uncaught ReferenceError: qaef_object is not defined
    at HTMLDivElement.<anonymous> (scripts.js?ver=1.3.10:23:28)    
    at HTMLDivElement.dispatch (jquery.min.js?ver=3.7.1:2:40035)    
    at v.handle (jquery.min.js?ver=3.7.1:2:38006)`
```
Prior to this error, a user message is generated:
`JQMIGRATE: Migrate is installed, version 3.4.1`.
I would like to implement grouped FAQs, and any ideas would help. Thanks

**Comment by SidVerson** [comment]
go to wp-content -> plugins -> quick-and-easy-faqs -> frontend -> js -> script.js and change all qaef_object to parent_toggle

**Comment by fahidjavid** [comment]
Thanks, @arkonisus; your PR has been merged, and this issue has been fixed.
