### ISSUE TITLE
How do you modify the sequence of Q&E FAQs?

### ISSUE THREAD

**Issue by qaefaq22** [InspiryThemes/quick-and-easy-faqs#4]
My FAQs need to be in a logical sequence on my Wordpress page to be useful for my users. How do I modify the sequence of Q&E FAQs which are all contained in a single group? As far as I can see FAQs in a group are not sequenced alphabetically or numerically.

**Comment by saqibsarwar** [comment]
FAQs are sorted in publish order. You can change the order by changing the publish date & time.
