### ISSUE TITLE
Remove font awesome icon font

### ISSUE THREAD

**Issue by marianrick** [InspiryThemes/quick-and-easy-faqs#6]
You should consider removing the `font-awesome.min.css` for the use of two easy icons, that can be achieved by using css only. You can [check this jsfiddle demo](https://jsfiddle.net/e40jLw2g/).

```
.icon {
  background: #7a7a7a;
  border-radius: 50%;
  color: #fff;
  display: inline-block;
  font-weight: bold;
  position: relative;
  height: 1.3em;
  width: 1.3em;
  margin-right: .3em;
  margin-top: -.2em;
  vertical-align: middle;
}

.show::after,
.hide::after {
  left: 50%;
  position: absolute;
  top: 50%;
  transform: translate(-50%, -55%);
}

.show::after {
  content: '+';
}

.hide::after {
  content: '-';
}
```

I was very happy to find such a "simple", well coded FAQ plugin. It may be better for use for professionals if you give the ability to deactivate the custom imports of your css, javascript and jQuery. This would offer developers full control over the look and feel, while they would although be able to reduce the server requests by including styles and scripts in their main-files.

Thanks for your good work! I really appreciate it.

**Comment by saqibsarwar** [comment]
@marianrick Thanks for your input, I will consider these points while working on next update.

Regards

**Comment by saqibsarwar** [comment]
I am working on this plugin's update and this suggestion is good but I have to drop this change request because many customers are using old icons and they have changed their colors etc on their websites. So this change can effect their website's appearance and that can create problems. So leaving it as it is. Thanks again for your input.

**Comment by elkegepunkt** [comment]
Sorry for reopening. How about a simple on / off switch to load (or not load) the font awesome styles?
