### ISSUE TITLE
Quick and Easy FAQ Sorting

### ISSUE THREAD

**Issue by hlarledge** [InspiryThemes/quick-and-easy-faqs#7]
I love your Quick and Easy FAQ plugin, but how do I change the sort order? The FAQs always list in the order they were created—even when I change the date on the FAQ item. Please tell me how I can correct this?

**Comment by saqibsarwar** [comment]
Hi,

Please try a sorting plugin like https://wordpress.org/plugins/simple-custom-post-order/screenshots/ and let me know how it goes.

Thanks & Regards
